version: '3.7'

services:
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - app-network
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
  api:
    container_name: api
    restart: on-failure
    build:
      context: ./store_api/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network
  app:
    container_name: app
    restart: on-failure
    build:
      context: ./store_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    links:
      - api
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

networks:
    app-network:
        driver: bridge

volumes:
  data: