version: '3.7'

services:
  api:
    container_name: api
    restart: on-failure
    build:
      context: ./store_api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: app
    build:
      context: ./store_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - '.:/app/store_app'
      - '/app/store_app/node_modules'
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true