version: '3.7'

services:

  react-web-base:
    container_name: store_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
