version: '3.7'

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
